baseURL = "https://sidverma.io/"
languageCode = "en-us"
title = "Sid Verma"
theme = "rocinante"
paginate = 3
summaryLength = 0

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[params]
  mode = "light"
  favicon = "/icons/favicon.ico"
  mainSections = ["posts", "photos"]
  email = "me@sidverma.io"
  about = """
Hi. I'm **Sid**. I write software code for a living.

Interested in humor, filmmaking, and a decentralized internet.

_I'm actively looking for work right now. Feel free to have a look at my resume below, and the rest of this website._
<br>
_My employment history includes <a href="https://shortform.com">Shortform</a>, <a href="https://opencraft.com">Opencraft</a>, <a href="https://mclarencollege.in">McLaren College</a>, <a href="https://www.tower-research.com" target="_blank">Tower Research Capital</a>, <a href="https://www.culturealley.com" target="_blank">CultureAlley</a> and <a href="https://www.smallcase.com" target="_blank">Smallcase</a> to name a few._
"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "/resume"
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Posts"
      href = "/posts"
    [[params.links.link]]
      name = "Photos"
      href = "/photos"
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/mavidser"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/mavidser"
      new_tab = true
