baseURL = "https://sidverma.io/"
languageCode = "en-us"
title = "Sid Verma"
theme = "rocinante"
paginate = 3
summaryLength = 0

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[params]
  mode = "light"
  customCSS = ["/css/style.css"]
  favicon = "/icons/favicon.ico"
  socialBanner = "/icons/banner.png"
  mainSections = ["posts", "photos"]
  email = "me@sidverma.io"
  about = """
Hi friend. I'm **Sid**!

This is my home on the internet. Come, have a tour. Please leave your shoes at the door.

I work with technology for a living - mostly as a software engineer. Some details are available in the resume below. In addition, I'm interested in filmmaking, tinkering with electronics, and building a decentralized internet. _Feel free to reach out if you'd like to work together._

I also like trees.
<br>
"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "/resume"
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Posts"
      href = "/posts"
    [[params.links.link]]
      name = "Photos"
      href = "/photos"
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/mavidser"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/mavidser"
      new_tab = true
