baseURL = "https://sidverma.io/"
languageCode = "en-us"
title = "Sid Verma"
theme = "rocinante-2"
paginate = 9999
summaryLength = 0

[markup]
  [markup.highlight]
    tabWidth = 2
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true

[params]
  colorScheme = "auto"
  customCSS = ["/css/style.css"]
  favicon = "/icons/favicon.ico"
  socialBanner = "/icons/banner.png"
  mainSections = ["posts", "photos"]
  specialEmail = "me@sidverma.io"
  about = """
Hey friend. I'm <b class="sway">Sid</b>.

This is my home on the internet. Come, have a tour. Please leave your shoes at the door.

I work with technology for a living - mostly as a software engineer. Some details are available in the resume below. In addition, I'm interested in filmmaking, tinkering with electronics, and building a decentralized internet.

I also like trees.

Email me if you'd like to work together. _Or if you just wanna chat._
<br>
"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "/resume"
      newTab = true
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      specialEmailLink = true
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/mavidser"
      newTab = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://instagram.com/mavidser"
      newTab = true

  [[params.links]]
    [[params.links.link]]
      name = "All Posts"
      href = "/posts"
    [[params.links.link]]
      name = "Photo albums"
      href = "/photos"
    [[params.links.link]]
      name = "List of tags"
      href = "/tags"
