baseURL = "https://sidverma.io/"
languageCode = "en-us"
title = "Sid Verma"
theme = "rocinante"
paginate = 3
summaryLength = 0

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.ico"
  mainSections = ["posts", "photos"]
  email = "me@sidverma.io"
  smart_email_link = ["Email"]
  about = """
Hi. I'm **Sid**. Some people also know me as Siddhartha.

I write software code for a living. For living, I take photographs, hike and bike across mountains, and explore filmmaking.

_I'm currently available for hire. Feel free to reach out if you think we might work well together._
<br>
_My previous employers are <a href="https://www.tower-research.com" target="_blank">Tower Research Capital</a>, <a href="https://www.culturealley.com" target="_blank">CultureAlley</a> and <a href="https://www.smallcase.com" target="_blank">Smallcase</a>._
"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "/SidVerma.Resume.pdf"
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/mavidser"
      new_tab = true
    [[params.links.link]]
      name = "Mastodon"
      href = "https://mastodon.social/@mavidser"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/mavidser"
      new_tab = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://instagram.com/mavidser"
      new_tab = true